name: ci-sonarcloud
on:
  pull_request:
    branches:
      - develop

jobs:
  run-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 #download new features add
      - uses: actions/setup-go@v2 #setup go enviroment
        with:
          go-version: 1.15
      - run: go test -coverprofile=coverage.out